# Generated by Django 4.0.3 on 2022-09-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_user_deleted_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video_serie',
            old_name='titre',
            new_name='title',
        ),
        migrations.AddField(
            model_name='video_serie',
            name='appartenir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartenir_serie', to='data.serie'),
        ),
    ]
