# Generated by Django 4.0.3 on 2022-09-06 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_video_video_video_serie_video_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.FileField(upload_to='logo/')),
            ],
        ),
    ]
