# Generated by Django 4.0.3 on 2022-09-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='logo_file',
        ),
    ]
