# Generated by Django 4.0.3 on 2022-09-08 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_logo_logo_logo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagecarousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='imagecarousel/')),
            ],
        ),
    ]
