version: "3.7"

services:
    db:
        image: postgres
        volumes:
            - ./back/db:/var/lib/postgresql/back
        environment:
         - POSTGRES_DB=Api
         - POSTGRES_USER=Api
         - POSTGRES_PASSWORD=H249hvdffqgtmmpfhnvuegfff@12#
         - POSTGRES_PORT=5432
        # ports:
        # - "5482:5432"

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
            # - ./static:/code/static/
            # - ./media:/code/media/
        ports:
            - "8000:8000"
        environment:
           - POSTGRES_NAME=postgres
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=JrmkIdc22@32311gf123@123
           - POSTGRES_PORT=5432
        depends_on:
            - db
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
